### ISSUE TITLE
Can't set border highlight

### ISSUE THREAD

**Issue by ram02z** [MunifTanjim/nui.nvim#1]
Hey,

I am using your rename script from https://github.com/MunifTanjim/dotfiles/blob/neovim-edge/private_dot_config/nvim/lua/config/lsp/custom.lua. I have tried to change the border highlight to `FloatBorder` and it doesn't change.

This is the relevant snippet:
```lua
local input = Input({
  border = {
    style = "rounded",
    highlight = "FloatBorder",
    text = {
      top = "[Rename]",
      top_align = "left",
    },
  },
...
```

Thanks for the library btw, I was waiting for a high level UI lib for a while! :D

**Comment by MunifTanjim** [comment]
Hello! Thanks for trying this out and reporting the bug! 😃 

This bug was happening when `border.text` was present.  I just pushed a fix for that.

**Comment by ram02z** [comment]
Thanks, the fix works!
