### ISSUE TITLE
Not all mappings are restored when popup is closed

### ISSUE THREAD

**Issue by darzok0914** [MunifTanjim/nui.nvim#100]
Hi, I've noticed an issue with some remaps. the issue doesn't occur all the time but often enough to be noticeable. I think I know why this occurs event though I wasn't able to reproduce the error consistently. 

in my config I have these remaps:
```lua
nnoremap <C-c> <C-w>c
tnoremap <C-c> <C-\><C-N><C-w>c
```

when using a popup, I remap ``` <C-c> ``` to something else. when I close the popup only ```tnoremap <C-c> <C-\><C-N><C-w>c``` is restored.

Hopefully these details can be helpful

**Comment by MunifTanjim** [comment]
Please add an example code that can reproduce it. I can't know anything for sure just from your description. For instance,

- how are you creating the popup?
- how are you doing the keymaps?

**Comment by MunifTanjim** [comment]
`:map` method add keymap for the popup's buffer. So when popup is `:unmount`-ed, those mappings are gone.

If you're passing `.bufnr` to `popup_options` (e.g. `local popup = Popup({ bufnr = 42 })`, then you'll need to manually cleanup those mapping when you `:unmount` popup, using the `:unmap` method.
