### ISSUE TITLE
Memory leak with NuiTree

### ISSUE THREAD

**Issue by cseickel** [MunifTanjim/nui.nvim#117]
I've discovered a memory leak in NuiTree, You can recreate it with this example:

```lua
local NuiLine = require("nui.line")
local NuiTree = require("nui.tree")

local nodes = {}
local i = 0
while i < 1000 do
  i = i + 1
  nodes[i] = NuiTree.Node({
    id = i,
    text = "Line " .. i,
  })
end

local winid = vim.api.nvim_get_current_win()
local bufnr = vim.api.nvim_create_buf(true, true)
vim.api.nvim_buf_set_name(bufnr, "NuiTree Test")
vim.api.nvim_win_set_buf(winid, bufnr)

local tree = NuiTree({
  winid = winid,
  nodes = nodes,
  buf_options = {
    bufhidden = "hide",
    buflisted = false,
    buftype = "nofile",
    filetype = "txt",
    swapfile = false,
  },
})
tree:render()

_G.refresh_tree = function()
  tree:render()
end
vim.api.nvim_buf_set_keymap(tree.bufnr, "n", "R", ":lua _G.refresh_tree()<cr>", {noremap = true, silent = true})
```

Then keep hitting `R` to refresh repeatedly. Every refresh leaks a little more memory, enough that it is obvious if you are watching the nvim process while you do it. Since I am using this for a sidebar file tree, it's normal for someone to leave it open all day, and it will re-render constantly as they work and new file events and diagnostics are fired.

I've tested against Neovim 6.1 and a more recent nightly. ~~I've had users report the leak from Windows, MacOS, and Linux.~~ EDIT: Strike that OS comment, I was confusing this with another issue. I can only confirm it happens on Linux, which is my own system.

**Comment by MunifTanjim** [comment]
Hey, can you check what this script does for you?

```lua
local nodes = {}
local i = 0
while i < 10000 do
  i = i + 1
  nodes[i] = "Line " .. i
end

local winid = vim.api.nvim_get_current_win()
local bufnr = vim.api.nvim_create_buf(true, true)
vim.api.nvim_buf_set_name(bufnr, "NuiTree Test")
vim.api.nvim_win_set_buf(winid, bufnr)

_G.refresh_tree = function()
  vim.api.nvim_buf_set_lines(
    bufnr,
    0,
    -1,
    false,
    vim.tbl_map(function(line)
      return line
    end, nodes)
  )
end

_G.refresh_tree()

vim.api.nvim_buf_set_keymap(bufnr, "n", "R", ":lua _G.refresh_tree()<cr>", { noremap = true, silent = true })
```

For me it also keeps taking more and more memory (but less than NuiTree, I guess because NuiTree does a lot more things).

Looks like it's got something to do with Neovim itself? 🤔

**Comment by cseickel** [comment]
Yup, that's the issue right there. I wouldn't say that this is any less than the full NuiTree example.

**Comment by MunifTanjim** [comment]
I'm guessing the issue is with this call: `vim.api.nvim_buf_set_lines(bufnr, 0, -1, ...)`, i.e. writing a buffer top-to-bottom over and over again. Neovim is probably not cleaning up something?

**Comment by cseickel** [comment]
> I'm guessing the issue is with this call: `vim.api.nvim_buf_set_lines(bufnr, 0, -1, ...)`, i.e. writing a buffer top-to-bottom over and over again. Neovim is probably not cleaning up something?

There could also be a leak in `vim.tbl_map`. Or maybe there's a subtle issue with the code, I'm not a lua expert yet... I can experiment with this later though.

**Comment by MunifTanjim** [comment]
I get the same result without the `vim.tbl_map`:

```lua
_G.refresh_tree = function()
  vim.api.nvim_buf_set_lines(
    bufnr,
    0,
    -1,
    false,
    nodes
  )
end
```

We should open an issue on the [neovim](https://github.com/neovim/neovim) repo.

**Comment by MunifTanjim** [comment]
Nevermind, pushed a commit to fix it: https://github.com/MunifTanjim/nui.nvim/commit/42552b3797c3452c5c94e0c84a04fbda9591b9d1

**Comment by cseickel** [comment]
@MunifTanjim thanks so much for the great library and figuring this out so quickly!

**Comment by nyngwang** [comment]
@MunifTanjim Thank you!
