### ISSUE TITLE
Support Themability

### ISSUE THREAD

**Issue by MunifTanjim** [MunifTanjim/nui.nvim#12]
User should be able to easliy apply custom highlight groups on specific part of the components. For example:

- Only change the color of Border Text

**Comment by alexzanderr** [comment]
and also if i can implement syntax highlithing on this, would be great.

i have this
![image](https://user-images.githubusercontent.com/54772464/134785609-2b852965-c24a-44e1-8b86-b606168aa3bc.png)

i would the colors the items with tree sitter or something.

**Comment by MunifTanjim** [comment]
Groundwork is done in #51

**Comment by MunifTanjim** [comment]
@alexzanderr I don't think treesitter would help you with syntax highlighting here. 🤔 

You can check the new [`NuiText`](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/text) and [`NuiLine`](https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/line). With those, you can highlight the text chunks on a line.

**Comment by alexzanderr** [comment]
okey thanks. you can close this

**Comment by MunifTanjim** [comment]
We're in a pretty good place right now with all the components. Closing it now.
