### ISSUE TITLE
weird highlight in input

### ISSUE THREAD

**Issue by jrafaaael** [MunifTanjim/nui.nvim#129]
As title says. I'm usign [onedark](https://github.com/navarasu/onedark.nvim)

![Screenshot_2022-06-21_20-23-45](https://user-images.githubusercontent.com/70046023/174917719-e2ae326d-4fd9-4be3-be08-8f6e49b64727.png)

**Comment by MunifTanjim** [comment]
@jrafaaael Can you provide example codes, please?

**Comment by MunifTanjim** [comment]
Looks like an issue with your color scheme. Here's a similar post: https://www.reddit.com/r/neovim/comments/v5jscg/question_floating_searchbox_border_highlight/

You'll need to fix the background for `FloatBorder` highight group.

**Comment by jrafaaael** [comment]
```
autocmd ColorScheme * highlight! link FloatBorder Normal
```
works for me! thanks!
