### ISSUE TITLE
Nui.menu not found 

### ISSUE THREAD

**Issue by Yoliani** [MunifTanjim/nui.nvim#15]
`local Menu = require("nui.menu")`

nui.menu' not found:
        no field package.preload['nui.menu']
        no file './nui/menu.lua'
        no file '/usr/share/luajit-2.1.0-beta3/nui/menu.lua'
        no file '/usr/local/share/lua/5.1/nui/menu.lua'
        no file '/usr/local/share/lua/5.1/nui/menu/init.lua'
        no file '/usr/share/lua/5.1/nui/menu.lua'
        no file '/usr/share/lua/5.1/nui/menu/init.lua'

**Comment by MunifTanjim** [comment]
It's looking into all the wrong paths 🤔 

Are you using Neovim and the plugin is properly installed?

**Comment by Yoliani** [comment]
I solved it by reinstalling nui
Thanks
