### ISSUE TITLE
nui.text and nui.line not highlighting the last character

### ISSUE THREAD

**Issue by X3eRo0** [MunifTanjim/nui.nvim#152]
I use nui.nvim to provide colors to my plugin via the nui.text and nui.line modules. After the recent commits [3775746](https://github.com/MunifTanjim/nui.nvim/commit/3775746f8324db1ff5068eaf10f321db5e566611) the highlighting of text was stopped at the last character.

Before commit [3775746](https://github.com/MunifTanjim/nui.nvim/commit/3775746f8324db1ff5068eaf10f321db5e566611)
![image](https://user-images.githubusercontent.com/24680989/179388682-555d92bd-58d3-4e4b-9e1c-134b549a3fc6.png)
After commit [3775746](https://github.com/MunifTanjim/nui.nvim/commit/3775746f8324db1ff5068eaf10f321db5e566611)
![image](https://user-images.githubusercontent.com/24680989/179388713-e6a95751-c0e2-4cce-8098-510b51c09e22.png)

If this commit was a fix to a bug then please let me know how do I fix my code to get proper highlighting, otherwise suggest a different solution.

**Comment by MunifTanjim** [comment]
@X3eRo0 Sorry about that. I read the extmarks documentation wrong. Reverted those changes.

And I'll improve the tests to catch these in future.

**Comment by X3eRo0** [comment]
Thanks 👍
