### ISSUE TITLE
Feature Request: Popup/Input component for passwords

### ISSUE THREAD

**Issue by d1saster** [MunifTanjim/nui.nvim#156]
It would be great to have some variant of Popup/Input displaying some prompt and without echoing the user input.

**Comment by MunifTanjim** [comment]
Can you try this and see if it works?

```lua
vim.api.nvim_buf_call(input.bufnr, function()
  vim.cmd([[
    setlocal conceallevel=2
    setlocal concealcursor=nvi
    syn region PasswordValue start=/^/ms=s+2 end=/$/ contains=PasswordChar
    syn match PasswordChar /./ contained conceal cchar=*
  ]])
end)
```

You can remove the `cchar=*` part to completely hide the characters.

**Comment by d1saster** [comment]
Wow that was a fast answer :) Yep works great. Thx.

Are you going to add this as an option to nui.nvim?

**Comment by MunifTanjim** [comment]
I don't want to add it in the library for now.

But added this in the wiki: https://github.com/MunifTanjim/nui.nvim/wiki/nui.input

I hope that helps.

**Comment by MunifTanjim** [comment]
@d1saster Now it's possible for you to have a `SecretInput` component in your project. I updated the wiki page with the guide for that: https://github.com/MunifTanjim/nui.nvim/wiki/nui.input#secretinput-component
