### ISSUE TITLE
random feedback

### ISSUE THREAD

**Issue by teto** [MunifTanjim/nui.nvim#16]
hi,

Thanks for doing this. I wanted to try out your menu implementation (I now use https://github.com/skywind3000/vim-quickui/issues) and wanted  to share some feedback:
1/ it would be nice if one could copy/paste the code from the readme to just test/run it but this doesn't work
```
local Menu = require("nui.menu")

local menu = Menu(popup_options, {
  lines = {
    Menu.item("Item 1"),
    Menu.item("Item 2"),
    Menu.separator("Menu Group"),
    Menu.item("Item 3"),
  },
  max_width = 20,
  separator = {
    char = "-",
    text_align = "right",
  },
  keymap = {
    focus_next = { "j", "<Down>", "<Tab>" },
    focus_prev = { "k", "<Up>", "<S-Tab>" },
    close = { "<Esc>", "<C-c>" },
    submit = { "<CR>", "<Space>" },
  },
  on_close = function()
    print("CLOSED")
  end,
  on_submit = function(item)
    print("SUBMITTED", vim.inspect(item))
  end
})

```
since popup_options is not defined. Also one needs to call `menu:mount()` afterwards.
I tried definining some but got `/pack/packer/start/nui.nvim/lua/nui/popup/init.lua:238: invalid border char`
Also screenshot/gif would be nice.

2/ If you are interested in notifications, you could talk to 
https://neovim.discourse.group/t/wip-animated-notifications-plugin/448/6
3/ there is a neovim project to provide some utilities https://github.com/nvim-lua/neovim-ui . Probably not as fancy as what you want to do but if yo uare interested in contributing, could be interesting.

**Comment by MunifTanjim** [comment]
> it would be nice if one could copy/paste the code from the readme to just test/run it but this doesn't work

That's a really good feedback. The documentation definitely needs to be improved.

>  tried definining some but got /pack/packer/start/nui.nvim/lua/nui/popup/init.lua:238: invalid border char

Since we don't have nicer documentation right now, maybe you can try the Menu example in this PR?

- https://github.com/MunifTanjim/nui.nvim/pull/10

> If you are interested in notifications, you could talk to https://neovim.discourse.group/t/wip-animated-notifications-plugin/448/6

I'll try to reach out... but did you meant `muniter` or `sunjon`? 🤔

> there is a neovim project to provide some utilities https://github.com/nvim-lua/neovim-ui . Probably not as fancy as what you want to do but if yo uare interested in contributing, could be interesting.

I'm aware of that project. I mentioned it in my [blogpost](https://muniftanjim.dev/blog/neovim-build-ui-using-nui-nvim) and wrote why I created a new project instead of contributing to it. In short, the API of `neovim-ui` and `popup.nvim` more low-level and they're intended to be merged into Neovim core in future. But `nui.nvim` aims to provide higher-level APIs than those.

**Comment by teto** [comment]
much better thanks for the snippet ! it worked well

Nice blogpost, I completely understand, I am happy to use your high-level api too. I am sure you have many ideas but here are some :p 
- cascading menu
- menu that is autofilled via menu_get("some_path"). 

As for the notifs I meant sunjeon

**Comment by MunifTanjim** [comment]
> menu that is autofilled via menu_get("some_path").

Hey, can you explain this one a bit? Maybe open another feature request issue with this?

**Comment by teto** [comment]
basically I would like to be able to replicate vim's mousemodel=popup_setpos in neovim https://github.com/neovim/neovim/issues/14921 , if you try a recent vim with that option, it opens up a menu that automatically loads the menus you 've defined via `:menu Popup.XXX`

**Comment by teto** [comment]
other question, I currently configure my menu in quickui via this mechanism [ description, command] : 
```
            \ ["Goto &Definition\t\\cd", 'lua vim.lsp.buf.definition()'],
            \ ["Goto &Declaration\t\\cd", 'lua vim.lsp.buf.declaration()'],
            \ ["Goto I&mplementation\t\\cd", 'lua vim.lsp.buf.implementation()'],
```
is it possible to do something similar with nui ? like
`    Menu.item("Item 1", "command1"),`

**Comment by MunifTanjim** [comment]
I just pushed a commit for support arbritary props in `Menu.item`. Here's the doc: https://github.com/MunifTanjim/nui.nvim/blob/77cefa67df7f282db20aa9afb5925aff79455dc2/README.md#menuitemitem-props

Now, you can do:

```lua
lines = {
    Menu.item("Item 1", { cmd = "lua vim.lsp.buf.definition()" }),
    Menu.item("Item 2", { func = function() vim.lsp.buf.declaration() end }),
},
on_submit = function(item)
  print("SUBMITTED", vim.inspect(item))

  if item.cmd then
    -- do something with it
  end

  if item.func then
    -- call it
  end
end,
```

So, you're not only limited to command strings. You can directly use Lua functions! 🎉

**Comment by teto** [comment]
thanks that works well :)
