### ISSUE TITLE
Layout made by splits

### ISSUE THREAD

**Issue by xeluxee** [MunifTanjim/nui.nvim#163]
Hi, thanks for maintaining this plugin

I'm trying to open three splits using a layout to get something like this
![split3](https://user-images.githubusercontent.com/88047141/181047598-e669bec9-d20d-4ffa-92ae-91f111bffe1a.png)

But the following code
``` lua
local Split = require("nui.split")
local Layout = require("nui.layout")

local split_one = Split({
  enter = true,
  relative = "win",
})
local split_two = Split({
  relative = "win",
})
local split_three = Split({
  relative = "win",
})

local layout = Layout(
  {
    relative = "editor",
    position = "bottom",
    size = 30,
  },
  Layout.Box({
    Layout.Box(split_one, { size = "50%" }),
    Layout.Box({
      split_two, { size = "50%" },
      split_three, { size = "50%" },
    }, { dir = "col" }),
  }, { dir = "row" })
)

layout:mount()
```

gives the following error
```
E5113: Error while calling lua chunk: .../site/pack/packer/start/nui.nvim/lua/nui/layout/init.lua:338: missing child.size                                      
stack traceback:                                                                                                                                               
        [C]: in function 'error'                                                                                                                               
        .../site/pack/packer/start/nui.nvim/lua/nui/layout/init.lua:338: in function 'Box'                                                                     
        splits.lua:23: in main chunk
```

**Comment by MunifTanjim** [comment]
Currently the `Layout` component only works with `Popup`.

But supporting `Split` is surely something I'd like to do.

**Comment by xeluxee** [comment]
FYI I've just implemented [split mode](https://user-images.githubusercontent.com/88047141/183751179-e07e2a4d-e2eb-468b-ba34-bb737cba4557.png) in my plugin [competitest.nvim](https://github.com/xeluxee/competitest.nvim)

I had a hard time looking for a solution to open splits correctly with the correct size.
Then I found out I had to disable `equalalways`, to enable/disable `winfixwidth` or `winfixheight` at the right time and to keep the cursor out of the current window to prevent it to be resized.

You can look at my implementation [here](https://github.com/xeluxee/competitest.nvim/blob/c86a94c5bd2a1edb69d2f77616005423a65949e0/lua/competitest/runner_ui/split.lua#L36-L117)
`layout`s are defined as tables, examples [here](https://github.com/xeluxee/competitest.nvim#customize-ui-layout)

**Comment by MunifTanjim** [comment]
Thanks for sharing that! @xeluxee 😃

https://github.com/MunifTanjim/nui.nvim/pull/165 does almost all the same things as your implementation. But I was struggling a bit with the sizing issue. The missing piece was setting `equalalways` to `false` before mounting and resetting it afterwards.

It'll try it out and try to merge that PR soon.

**Comment by MunifTanjim** [comment]
Turns out modifying `equalalways` is not a good idea. The moment `equalalways` is enabled, all the splits are automatically resized... so that defeats the purpose.

Anyway, #165 just got merged. NuiSplit can now be used with NuiLayout.

**Comment by xeluxee** [comment]
Great, thanks! I'll try it out as soon as possible

> Turns out modifying `equalalways` is not a good idea. The moment `equalalways` is enabled, all the splits are automatically resized... so that defeats the purpose.

I'm not experiencing this behaviour in my plugin. I'll look into it
