### ISSUE TITLE
Can't use `split` when `winbar` is set

### ISSUE THREAD

**Issue by loctvl842** [MunifTanjim/nui.nvim#172]
I got this error only when set `winbar`:
![image](https://user-images.githubusercontent.com/80513079/182396776-19dfb2c1-8866-480f-b50e-8878c0632823.png)
It's normal when no `winbar` is set.
But after i `setlocal winbar={any value}`. The file can run only when the cursor is in the first line.
![image](https://user-images.githubusercontent.com/80513079/182397465-49537de9-143f-4e97-a777-75dde34a1639.png)
But if not, I got this error:
![image](https://user-images.githubusercontent.com/80513079/182397592-188211d6-693b-4c13-aeaf-bf36eda9258f.png)
(NOTICE: the cursor is on line 2)

**Comment by MunifTanjim** [comment]
I think this might be related to the neovim core issue: https://github.com/neovim/neovim/issues/19458

**Comment by MunifTanjim** [comment]
Closing this since https://github.com/neovim/neovim/issues/19458 got fixed by https://github.com/neovim/neovim/pull/19751
