### ISSUE TITLE
Memory leak if namespace isn't cleared

### ISSUE THREAD

**Issue by cseickel** [MunifTanjim/nui.nvim#175]
I've discovered that each render of the tree will leak memory if the namespace isn't cleared first. I fixed the problem in Neo-tree by wrapping all renders in a function that clears the namespace like this:

```lua
  vim.api.nvim_buf_clear_namespace(tree.bufnr, highlights.ns_id, 0, -1)
  tree:render()
```
(this is part of https://github.com/nvim-neo-tree/neo-tree.nvim/pull/475)

Should this be done implicitly in the tree's render function, or added at a lower level somewhere? If there are reasons why it shouldn't be done implicitly, I think there should be something in the documentation to explain when it should be done.

**Comment by MunifTanjim** [comment]
Nice catch! I completely missed it.

> Should this be done implicitly

Yep, this should be done automatically.

> tree's render function, or added at a lower level somewhere? 
The `:unmount` method would be a more proper place.

> If there are reasons why it shouldn't be done implicitly

If a custom namespace id is being used, there's no reason to not do it.

But if the component is using the fallback namespace id (https://github.com/MunifTanjim/nui.nvim/blob/95319774b31558479c71e9b190870aae7bd8e49f/lua/nui/utils/init.lua#L78) which kinda works as a global namespace, we can't clear that. Because multiple components would be affected by that.

**Comment by cseickel** [comment]
> which kinda works as a global namespace, we can't clear that. Because multiple components would be affected by that.

You can probably assume that there is only one client per buffer, so I would think it is safe to clear that buffer's namespace. This is definitely true for a tree or a popup. It's possible but hard to imagine why someone would write NuiLines to a buffer that might be shared with other plugins that are also using Nui.

**Comment by MunifTanjim** [comment]
Ah yes, you're absolutely right, the clearing only happens per buffer. So it's safe to clear it when the buffer is destroyed.

**Comment by MunifTanjim** [comment]
But is it safe to clear it on render? 🤔 @cseickel

**Comment by cseickel** [comment]
> But is it safe to clear it on render? 🤔 @cseickel 
> 

It seems to work correctly for what I am doing. Since render rewrites the whole buffer, I think it is correct. If you ever move to a change detection with incremental updates, then it would probably break.

**Comment by MunifTanjim** [comment]
It's kinda possible to render the `nui.tree` in a specific region of a buffer and have content before and after the tree.

For example, you can have a buffer like this:

```
HEADER



FOOTER
```

and then do:

```lua
tree:render(3)
```

the header and footer will remain intact. If those header and footer region have some text with extmarks, it would break if we automatically clear the namespace on tree render.

**Comment by MunifTanjim** [comment]
I'm also wondering, is it possible for neovim core to clear unused extmarks not in use automatically. At least when buffer is deleted, neovim core should automatically do it for that buffer 🤔

**Comment by cseickel** [comment]
> It's kinda possible to render the `nui.tree` in a specific region of a buffer and have content before and after the tree.

🤯 🤯 🤯 I had no idea! Now that I know, I am going to use that...

This reminds that the last two arguments to the clear function are the lines, so you can just specify the range of lines to clear. I think this should be known, and this also means that you can implicitly clear even on an individual NuiLine.

> I'm also wondering, is it possible for neovim core to clear unused extmarks automatically. At least when buffer is deleted, neovim core should automatically do it for that buffer 🤔

That is what I would have expected. I guess this is where the line between lua and C breaks down and it becomes fuzzy which memory management model is in effect.

**Comment by MunifTanjim** [comment]
Can you try out https://github.com/MunifTanjim/nui.nvim/pull/176 and see if it works alright?

**Comment by cseickel** [comment]
Thanks for the quick action on this!
