### ISSUE TITLE
Helper for creating Complex Layouts

### ISSUE THREAD

**Issue by MunifTanjim** [MunifTanjim/nui.nvim#18]
Depends on:

- https://github.com/neovim/neovim/pull/14770

Potential blockers:
- https://github.com/neovim/neovim/issues/18925

---

Something like this: https://github.com/nvim-lua/neovim-ui/issues/4#issuecomment-774148707. But should have a more declarative, friendly, easy to use interface. It would be great if the developer didn't have to calculate anything in their head.

**Comment by MunifTanjim** [comment]
Is there a way to make the whole thing stateless? 🤔 For example:

Have a function `layout`, that takes two things:

- `size` and `position` of the whole thing (all the components will fill up this space).
- something that describes how the components will be arranged and their size.

And the function will return the calculated `size` and `position` of the whole thing and a list of items where each item contains the `size` and `position` of the individual components.

Maybe it can look like this:

```lua
local result = layout(
  { size = "80%", position = "50%" },
  {
    vbox({ size = "50%" }, {
      hbox({ size = "70%" }),
      hbox({ size = "30%" })
    }),
    vbox({ size = "50%" })
  }
)

local container = result.container
local t, i, p = result.T, result.I, result.P

-- container, t, i, p all will have .size and .position
```

```
--------------
|  TT  |  P  |
|  TT  |  P  |
|------|  P  |
|  II  |  P  |
--------------
```

**Comment by MunifTanjim** [comment]
Or better yet, can we just pass the visual thing to `layout` function?

```lua
local result = layout({ size = "80%", position = "50%" }, [[
--------------
|  TT  |  P  |
|  TT  |  P  |
|------|  P  |
|  II  |  P  |
--------------
]])
```

😂

**Comment by cseickel** [comment]
> Is there a way to make the whole thing stateless? 🤔

I am a big fan of stateless, but as a consumer I would prefer this be a declarative API where all I have to do is define the layout and let a `LayoutManager` apply those sizes. I would also want that layout manager respond to changes and reapply the layout automatically. Does that fit with your expectations?

I do like the way you define the layout with named cells instead of inserting the windows themselves. That is a much better idea. 

What I would want add is methods on the container to set the contents of a cell and apply the layout:

```lua
local result = layout(
  { size = "80%", position = "50%" },
  {
    vbox({ size = "50%" }, {
      hbox("T", { size = "70%" }),
      hbox("I", { size = "30%" })
    }),
    vbox("P", { size = "50%" })
  }
)

-- then

local input = Input(...)
local t_popup = Popup(...)
local p_popup = Popup(...)
container.set_window("I", input)
container.set_window("T", t_popup)
container.set_window("P", p_popup)

-- or

container.set_windows({
  "I" = input,
  "T" = t_popup,
  "P" = p_popup,
})

-- maybe later

local new_p = Popup(...)
container.set_window("P", new_p)

-- and then to recalculate and actually set the size and position of each window:
container.apply()

-- which can also be hooked up to an autocmd if we export the container

vim.cmd([[
  au VimResize * lua require("my.module").container.apply()
]])
```

**Comment by MunifTanjim** [comment]
Sounds good! 👍🏼 

Here's an additional thing to what you said above:

```lua
local Layout = require('nui.layout')

local layout_options
 -- create a new floatting window for using as container
layout_options = { size = "80%", position = "50%" }
-- or use an existing window as container
layout_options = { winid = 42 }

local components =  {
  vbox({ size = "50%" }, {
    hbox("T", { size = "70%" }),
    hbox("I", { size = "30%" })
  }),
  vbox("P", { size = "50%" })
}

local layout = Layout(layout_options, components)

-- create new window if needed or do nothing if winid is provided
layout:mount()
```

I think this is a good place to start. Once we have something that works we can tweak the APIs and names later.

**Comment by MunifTanjim** [comment]
Also we can add a new internal (for now) method to `popup` called `_set_layout` that takes `{ size, position, relative }` and performs what `set_size` and `set_position` does together (so that only a single `nvim_win_set_config` call is made).

`nui.layout` can call this `_set_layout` method to resize and reposition the components.

**Comment by cseickel** [comment]
This is different from what I was expecting:

```lua
local layout_options
 -- create a new floatting window for using as container
layout_options = { size = "80%", position = "50%" }
-- or use an existing window as container
layout_options = { winid = 42 }
```
...
```lua
-- create new window if needed or do nothing if winid is provided
-- (maybe even call `:mount` for all the components?)
layout:mount()
```

I was thinking of the `layout` being a purely logical concept without being tied to an actual window. The child windows are then arranged in a cluster as siblings rather than actually being contained inside of something else. To that end, I wouldn't have a `mount()` method but the `apply()` would handle calculating the sizes and positions, and then iterating over all of the child windows and either call `mount` or `_set_layout` on them as appropriate.

Does that make sense or am I missing something?

**Comment by MunifTanjim** [comment]
Hmm 🤔 

Well, here's a wild scenario. Have this in a buffer:

```ts
const something = {
  a: 1,
  b: 2,
}

console.log(something)
```

Now I want to rename the `something` variable. I put the cursor on `something` and start the renaming process, I want to see this:

```
-[Rename]--------------------
|> something                |
-----------------------------
| 1: const something = {    |
| 5: console.log(something) |
-----------------------------
```

The first component is a `nui.input` and as I change the value, I want to see which line numbers will change along with the updated content. So if I change the value to `foo`, I see:

```
-[Rename]--------------------
|> foo                      |
-----------------------------
| 1: const foo = {          |
| 5: console.log(foo)       |
-----------------------------
```

So far so good. Now I want this whole layout positioned relative to the buffer position `(1, 15)`, i.e. 15 the character of 1st line. So when I scroll, the whole layout will still be relative to that buffer position.

Will this be possible if layout does not create a separate window? 🤔

**Comment by cseickel** [comment]
That is an interesting use case, has anyone made that style of rename yet?

> So far so good. Now I want this whole layout positioned relative to the buffer position (1, 15), i.e. 15 the character of 1st line. So when I scroll, the whole layout will still be relative to that buffer position.

I have never thought of that before, is there a way to make a floating window anchored to a specific buffer position so that it moves when you scroll the buffer? On the same train of thought, can you make other floating windows be locked to the position of a parent floating window so that they move when it moves? I hadn't thought about this as a hierarchy before, I thought all floating windows were stored in a flat array as siblings without any relation to each other.

**Comment by MunifTanjim** [comment]
> That is an interesting use case, has anyone made that style of rename yet?

Not that I know of 😂 But stuffs like this are definitely possible.

> is there a way to make a floating window anchored to a specific buffer position so that it moves when you scroll the buffer?

I think it can be done using:

```lua
local popup = Popup({
  ...
  relative = {
    type = "buf",
    position = { row = 0, col = 14 },
  },
  ...
})
```

On the same train of thought, can you make other floating windows be locked to the position of a parent floating window so that they move when it moves?

```lua
local popup = Popup({
  ...
  relative = {
    type = "win",
    winid = 42,
  },
  ...
})
```

You can find the low-level details in `:help api-win_config`.

**Comment by cseickel** [comment]
I didn't realize that relative positioning update itself when you move the window that it was relative to, but I tested it out and it works. I had trouble defining this using Popup though, I think there may be issue with that documentation or implementation. I'll circle back on that when I get to that point in this work.

I will use the parent window concept now that I know about this feature.

**Comment by cseickel** [comment]
I have been kind of stalled on this between work my own plugin and watching the news... I still may do this, but I'm not sure. If anyone else had interest, please feel free to jump in.

**Comment by MunifTanjim** [comment]
Initial implementation merged with https://github.com/MunifTanjim/nui.nvim/pull/120.

Some additional features will need to be implemented in the future.
