### ISSUE TITLE
Maps before mounting, input prefix

### ISSUE THREAD

**Issue by levouh** [MunifTanjim/nui.nvim#2]
Using the following:

```
local Input = require('nui.input')

local popup_options = {
  border = {
    style = { '╭', '─', '╮', '│', '╯', '─', '╰', '│' },
    highlight = 'FloatBorder',
    text = {
      top = ' Git ',
      top_align = 'left',
    },
  },
  position = '50%',
  size = {
    width = '80%',
    height = '60%',
  },
  opacity = 1,
}

local input = Input(popup_options, {
  prefix = 'Push to branch master? [y/N]: ',  -- Does not work
  default_value = '',
  on_close = function()
    print('Input closed!')
  end,
  on_submit = function(value)
    print('Value submitted: ', value)
  end,
  on_change = function(value)
    print('Value changed: ', value)
  end,
})

-- Does not work (as expected based on the code as the window isn't mounted), but putting these after :mount() doesn't work either, might be a prompt-buffer thing?
input:map('n', 'y', input.input_props.on_submit, { noremap = true }, true)
input:map('n', 'n', input.input_props.on_close, { noremap = true }, true)

input:mount()
```

there are two things that I haven't been able to get to work and have questions on.

1. When running `luafile %` on the above text in a buffer, it results in an error noting that the `popup` must be `:mount()`-ed before calling `:map()`. However, if I move the `:map()` call to _after_ the `:mount()` call, the mappings aren't applied. It seems like this might be a byproduct of the `:h prompt-buffer` window, but wanted to confirm that I'm not doing something wrong.
2. The `prefix` notably doesn't show up, and the `Input` popup ends up looking like this:

![image](https://user-images.githubusercontent.com/31262046/126071462-0eb7224d-2cd8-43bf-9393-afd27f5f76a6.png)

when ideally (as noted for the `:h prompt-buffer`) the `prefix` text would be a non-editable prefix, but it doesn't actually show up.

**Comment by MunifTanjim** [comment]
Hey, I really appreciate you trying this out. 😃 

> When running luafile % on the above text in a buffer, it results in an error noting that the popup must be :mount()-ed before calling :map(). However, if I move the :map() call to after the :mount() call, the mappings aren't applied. It seems like this might be a byproduct of the :h prompt-buffer window, but wanted to confirm that I'm not doing something wrong.

We need the buffer id `bufnr` to apply the keymaps, so mounting the component before mapping is necessary.

`Input` was not really designed to behave like you need it here. The initial mode is `INSERT` after the component is mounted. As you're mapping for `"n"` normal mode, it's not working.

There will eventually be a dedicated component to for your exact usecase, where you press a specific key to choose a option (YES/NO). 

For now  you can try something like this with `Input`

```lua
  local input = Input(popup_options, {
    prompt = "Push to branch master? [y/N]: ",
    default_value = '',
  })

  input:mount()

  input:map("i", "y", function()
    input.input_props.on_submit()
    vim.api.nvim_command("stopinsert")
    print("YES")
  end, { noremap = true }, true)

  input:map("i", "n", function()
    input.input_props.on_submit()
    vim.api.nvim_command("stopinsert")
    print("NO")
  end, { noremap = true }, true)
```

or you can use the base `Popup` to implement the desired behavior. In case you decide to use the base `Popup` compnent, it'll be really helpful if you can drop a link to your implementation here 😃 ]

> The prefix notably doesn't show up, and the Input popup ends up looking like this:

Sorry about that. The README has a typo. It should be `prompt` instead of `prefix`.

**Comment by levouh** [comment]
Didn't even think twice about the `n` map option, that makes complete sense.

Want me to leave this open to fix the documentation @MunifTanjim? Otherwise I'll go ahead and close it.

**Comment by MunifTanjim** [comment]
> Want me to leave this open to fix the documentation @MunifTanjim? Otherwise I'll go ahead and close it.

I'd love contributions from people 😃 I already fixed this one tho.

Before you go, here's another idea:

```lua
local content = " Push to branch master? [y/N] "

local popup_options = {
  enter = true,
  border = {
    style = { '‚ï≠', '‚îÄ', '‚ïÆ', '‚îÇ', '‚ïØ', '‚îÄ', '‚ï∞', '‚îÇ' },
    highlight = 'FloatBorder',
    text = {
      top = ' Git ',
      top_align = 'left',
    },
  },
  highlight = "Normal:Normal",
  position = '50%',
  size = {
    width = #content,
    height = 1,
  },
  opacity = 1,
}

local popup = Popup(popup_options)

popup:mount()

vim.api.nvim_buf_set_lines(popup.bufnr, 0, 1, false, { content })
vim.api.nvim_buf_set_option(popup.bufnr, "modifiable", false)
vim.api.nvim_buf_set_option(popup.bufnr, "readonly", true)

popup:map("n", "<esc>", function()
  popup:unmount()
end, { noremap = true })

popup:map("n", "y", function()
  popup:unmount()
  print("YES")
end, { noremap = true })

popup:map("n", "n", function()
  popup:unmount()
  print("NO")
end, { noremap = true })
```

**Comment by levouh** [comment]
I like it!

I was thinking about doing virtual text, where `CursorMovedI` would clear it and then it would be reinstantiated it when `on_change` input prop value is empty, etc.

Either way, thanks for the help. I'm sure I'll be back as I continue migrating all my own personal jank-window handling over to this :wink:
