### ISSUE TITLE
Lualine bar is disappearing when resizing tmux window or unsuspending vim.

### ISSUE THREAD

**Issue by art-romaniuk** [MunifTanjim/nui.nvim#210]
Reproducing problem:

Tmux
1. Open vim in tmux (lualine bar is present)
<img width="2051" alt="Screenshot 2022-11-10 at 13 02 26" src="https://user-images.githubusercontent.com/30126491/201074995-75f7d430-2aba-47b7-b6af-075e9ed862b5.png">
 2. Split tmux horizontally (lualine bar is disappeared)
<img width="2054" alt="Screenshot 2022-11-10 at 13 08 58" src="https://user-images.githubusercontent.com/30126491/201076093-adeba63e-35d2-4f89-8e7a-8ee21cece7d4.png">

 Vim
 1. Open vim (lualine bar is present)
 2. Press Ctrl-z combination to suspend vim
 3. Run command `fg` to unsuspend vim (lualine bar is disappeared)

**Comment by MunifTanjim** [comment]
And how is this related to `nui.nvim`? 🤔

**Comment by art-romaniuk** [comment]
Oh, sorry, this issue refers to `folke/noice.nvim`.

**Comment by MunifTanjim** [comment]
In that case closing it...

**Comment by art-romaniuk** [comment]
Yes, thanks.
