### ISSUE TITLE
Feature request: event for popup unmount

### ISSUE THREAD

**Issue by danielo515** [MunifTanjim/nui.nvim#214]
Hello.
Now that we have layouts, it is not uncommon to have complex arrangements of popus or splits that are tied together.
It will be cool to have an event when a popup is unmounted, so you can perform some cleanup related to that specific popup (for example, cleanup buffer bindings).
Please note that the existing BufLeave or BufWinLeave are just not enough, because, if you have, for example, a side by side layout, you may be switching between the two popups/splits, and running cleanup on BufLeave events is not desirable.

The only workaround that I can think for now is to set BufEnter + BufLeave events that removes and re-attaches the specific keybindings. However this is a bit messy and not yet enough because, if you are displaying existing buffers, you still leak the BufEnter or BufLeave events.

Will love to hear your thoughts on this.

**Comment by MunifTanjim** [comment]
Have you considered extending the Popup component for your specific use-case?

```lua
local MyPopup = Popup:extend("MyPopup")

function MyPopup:unmount()
  -- do stuffs before unmount
  MyPopup.super.unmount(self)
  -- do sutuffs after unmount
end

local popup = MyPopup(options)

popup:mount()
popup:unmount()
```

**Comment by danielo515** [comment]
That is actually a great suggestion! Is there any internal property where maps are stored? Or do I have to extend the map methods in order to register them?

**Comment by MunifTanjim** [comment]
> Is there any internal property where maps are stored?

`popup:map` is just a sugar on top of neovim's `vim.keymap.set` or `nvim_buf_set_keymap`.

`nui.nvim` doesn't store them anywhere. If you want to store them, you'll need extend the `:map` method.

**Comment by danielo515** [comment]
Extending is exactly what I wanted.
