### ISSUE TITLE
Could you support shadow border?

### ISSUE THREAD

**Issue by nyngwang** [MunifTanjim/nui.nvim#217]

**Comment by MunifTanjim** [comment]
Did you try setting `"shadow"` as `border.style`?

```lua
local popup = Popup({
  border = {
    style = "shadow",
  },
  -- ....
})
```

![image](https://user-images.githubusercontent.com/8050659/208057631-1ee8d4ad-7bb5-4e96-b138-293d52bd9029.png)

**Comment by nyngwang** [comment]
Yes. I'm a user of `folke/noice.nvim` and it `requires` your plugin. I did try it there:

```lua
size = { width = '50%' },
border = { style = 'shadow' }, -- here
```

I'm asking here because I want to bisect the cause of the problem. Now I believe this is a bug of `folke/noice.nvim`.

**Comment by MunifTanjim** [comment]
I just saw the related issue: https://github.com/folke/noice.nvim/issues/266

Unfortunately, shadow border can't support text (since it doesn't really have any border to put the text on).

Closing the issue.

**Comment by nyngwang** [comment]
Well, I think maybe I don't get what you meant by:

> [...] shadow border can't support text (since it doesn't really have any border to put the text on).

Then why which-key can do this:

<img src="https://user-images.githubusercontent.com/24765272/208063406-ec5fd0bb-26ec-485e-a44f-568377722a38.png" width="500">

**Comment by MunifTanjim** [comment]
Border text is different. It's when you have text on the border, for example:

![image](https://user-images.githubusercontent.com/8050659/208063919-88bba241-debc-453f-9788-bad1cec0264b.png)

^ `"[Rename]"` on this screenshot.

**Comment by nyngwang** [comment]
@MunifTanjim Thanks for your kindness, you just made better explanation than the author :) Then where should I put the `style` to achieve the same effect as the image I post?

**Comment by MunifTanjim** [comment]
`noice.nvim` is probably setting the `border.text` internally. So it's getting merged with your config and ends up being: `{ border = { style = "shadow", text = { --[[ something set by noice ]] } } }`, which is not supported.

I don't know about the `noice.nvim` internals, so you'll need to discuss it on that project.

**Comment by nyngwang** [comment]
@MunifTanjim I did, but he hasn't replied. No worries, I think he's busy with something more important. Again thanks for your detailed reply :)

**Comment by MunifTanjim** [comment]
Well, you created issues on both repo with absolutely no description. That was a bad way of submitting issues.

Issues should be created with proper description - details about what you tried, what you're expecting and what's happening. Provide as much information as you can. Otherwise plugin maintainers can't just guess the problem you're facing.

I hope it helps when you face any problems in future.

**Comment by nyngwang** [comment]
You're right. I have no excuse then.
