### ISSUE TITLE
Input problem!

### ISSUE THREAD

**Issue by RAprogramm** [MunifTanjim/nui.nvim#232]
When i open file via neo-tree and then trey to do something like:
`lua goGet:mount()` in command-mode
this function for example:

``` 
_G.goGet = Input({
  position = '50%',
  size = { width = 70 },
  border = {
    style = 'rounded',
    text = {
      top = ' Package link: ',
      top_align = 'center',
      bottom = '(you can provide more than one package url)',
    },
    padding = { 0.5, 1 },
  },
  relative = 'editor',
  win_options = {
    winhighlight = 'Normal:Normal,FloatBorder:VertSplit',
  },
}, {
  prompt = '',
  default_value = '',
  on_close = function()
    require('notify').notify('Getting packages canceled!', 'error')
  end,
  on_submit = function(value)
    vim.fn.execute('GoGet ' .. value)
    vim.fn.execute('LspRestart')
  end,
})
goGet:on(event.BufLeave, function() inputMod:unmount() end)
```

i have message like that and no action.
`^I...i/.local/share/nvim/lazy/nui.nvim/lua/nui/input/init.lua:81: in function <...i/.local/share/nvim/lazy/nui.nvim/lua/nui/input/init.lua:80>
`

but when file opened from telescope for example - all is good

**Comment by RAprogramm** [comment]
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/674

**Comment by MunifTanjim** [comment]
Can you share the whole error? It's hard to know what's wrong from only those 2 lines.

**Comment by MunifTanjim** [comment]
Anyway, try not to re-use the input. Try doing something like this instead:

```lua
_G.open_input = function(opts)
  local input = Input({
    -- popup options
  }, {
    -- input options
  })
  input:on(event.BufLeave, function() input:unmount() end)
  input:mount()
end
```

And call `open_input` function to use the input.

**Comment by RAprogramm** [comment]
How I can do that?

**Comment by MunifTanjim** [comment]
> How I can do that?

Sharing the whole error? You're probably using some notification plugin that overrides `vim.notify` function. If that's the case, then disabling that plugin would print the whole error in neovim's commandline (at the bottom).

**Comment by RAprogramm** [comment]
OH! It helps! now works good! thank you!
