### ISSUE TITLE
Popup does not maintain the desired position on resize.

### ISSUE THREAD

**Issue by jackMort** [MunifTanjim/nui.nvim#235]
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.01.20-10_47_37.webm](https://user-images.githubusercontent.com/163699/213665598-fffc30d2-0618-4390-a90a-173b9a09ca37.webm)

as on preview video.
here's the popup definition:
```
popup = Popup({
      position = { row = 0, col = "100%" },
      size = {
        width = 1,
        height = HEIGHT,
      },
      focusable = false,
      relative = "win",
      border = {
        style = "none",
      },
      buf_options = {
        modifiable = true,
        readonly = false,
      },
      win_options = {
        winblend = 30,
        winhighlight = "Normal:,FloatBorder:",
      },
    })

```

**Comment by MunifTanjim** [comment]
This is expected. Nui components do not react to resize events by default.

You can try something like this:

```lua
vim.api.nvim_create_autocmd("WinResized", {
  group = vim.api.nvim_create_augroup("refresh_popup_layout", { clear = true }),
  callback = function()
    popup:update_layout()
  end,
})
```

`popup:update_layout()` resizes and repositions the popup.

Note: `WinResized` event is not available in older Neovim.

**Comment by jackMort** [comment]
Great, thank you!
