### ISSUE TITLE
nui.layout not found

### ISSUE THREAD

**Issue by Winter-Joy** [MunifTanjim/nui.nvim#239]
The version of neovim is 0.7.2.
The operation system is ubuntu22.
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/41278235/218927900-e578be92-632c-4151-b248-f9b7cda11abe.png">
I can use other  components but layout. I dont't know what hanppens.

**Comment by MunifTanjim** [comment]
You're probably using an old version of `nui.nvim`. Try to update it?

**Comment by Winter-Joy** [comment]
I have installed the latest version with plug, but it still doesn't work.There is no module 'nui.layout'

**Comment by MunifTanjim** [comment]
Are you using `packer` or `plug`?

**Comment by Winter-Joy** [comment]
I know what happened.I use the mirror of github, the version in the mirror is not the latest.
