### ISSUE TITLE
popup:update_layout is resetting win_options

### ISSUE THREAD

**Issue by pitkling** [MunifTanjim/nui.nvim#250]
Assume I have a `layout` that contains a popup for which `win_options.number = true` is set (or a similar window option). These options are set for the window on `Popupp:_open_window()`. But if the layout with the popup is visible and i call `layout:update(…)` (the updated layout still containing the same popup with the number option set), the numbering is lost. I would expect the `win_options` to be conserved during such an update. As a simple workaround, one can call `layout:hide()` before and `layout:show()` after the `layout:update(…)`.

The behavior is probably due to the layout update eventually calling `vim.api.nvim_win_set_config` for the popup, which by default sets the window style to `minimal`. This clears things like the `number` option. It seems one should reapply the window options via a call to `_.set_win_options(self.winid, info.win_options)` after the call to `vim.api.nvim_win_set_config` in:

https://github.com/MunifTanjim/nui.nvim/blob/4eaec2ac66af2ca6ddddd3f665ad0909b90ae36a/lua/nui/popup/init.lua#L363-L365

**Comment by MunifTanjim** [comment]
Related Upstream Issue: https://github.com/neovim/neovim/issues/20370

**Comment by pitkling** [comment]
Thanks for the quick fix!
