### ISSUE TITLE
Error in apply_workaround_for_float_relative_position_issue_18925

### ISSUE THREAD

**Issue by Leo310** [MunifTanjim/nui.nvim#252]
The problem is described here:
https://github.com/jackMort/ChatGPT.nvim/issues/128

As the error appears to come out of nui.nvim I am opening this issue with the hope that you maybe have an idea of what is going on.

**Comment by MunifTanjim** [comment]
How to reproduce? Can you share minimal reproduction steps please?

**Comment by Leo310** [comment]
I explained the problem in the original issue, but maybe I should have made the steps more clear.

To reproduce:
1. get my chatgpt.nvim [lua config](https://github.com/jackMort/ChatGPT.nvim/issues/128#issuecomment-1492602684)
2. install the latest ChatGPT.nvim with Lazy
3. Setup ChatGPT.nvim as described in the [README](https://github.com/jackMort/ChatGPT.nvim) (providing OpenAI API-Key...)
4. Run the command :ChatGPT
5. Try to submit a prompt -> Error with the provided Stack-Trace

[But not everyone seems to face this problem.](https://github.com/jackMort/ChatGPT.nvim/issues/128#issuecomment-1493430414) So I am not sure if you would be able to reproduce it.

**Comment by MunifTanjim** [comment]
Can you reproduce this on a clean neovim setup?

It might be caused by one of the plugins you are using. That'd be the reason why it's not reproducible by everybody.

**Comment by Leo310** [comment]
Yeah you were right. For whatever reason, this [plugin](https://github.com/jiangmiao/auto-pairs) was causing the issue.

**Comment by MunifTanjim** [comment]
I think that plugin remaps `<CR>` and some other keys for every buffer: https://github.com/jiangmiao/auto-pairs/blob/39f06b873a8449af8ff6a3eee716d3da14d63a76/plugin/auto-pairs.vim#L603-L673

Ideally, it should ignore scratch buffers (https://neovim.io/doc/user/windows.html#scratch-buffer).
