### ISSUE TITLE
Evenly spaced splits in box layout

### ISSUE THREAD

**Issue by rcarriga** [MunifTanjim/nui.nvim#253]
Hey there, I'm looking at using nui.nvim within nvim-dap-ui as it seems like it'd offer more flexibility to users and also allow me to reduce the size of the code :smile: I'm trying to figure out how to replicate the default config which has 4 windows to the left and 2 windows at the bottom

![image](https://user-images.githubusercontent.com/24252670/191198389-a1321363-c0f1-4ff1-b663-ab1350d2b393.png)

Right now I've got this
```lua
local Layout = require("nui.layout")
local Split = require("nui.split")

local cur_win = vim.api.nvim_get_current_win()
local col_layout = Layout(
  {
    position = "left",
    relative = "editor",
    size = "20%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
  }, {
    dir = "col",
  })
)

col_layout:mount()

vim.api.nvim_set_current_win(cur_win)

local row_layout = Layout(
  {
    position = "bottom",
    relative = "editor",
    size = "25%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "50%" }),
    Layout.Box(Split({}), { size = "50%" }),
  }, {
    dir = "row",
  })
)

row_layout:mount()
```
but this results in the windows not being evenly spaced
![image](https://user-images.githubusercontent.com/24252670/230955500-e65df902-7df5-4191-a3e0-a5cc4dc3084f.png)

Is there something I'm doing wrong?

**Comment by MunifTanjim** [comment]
Hey @rcarriga , can you check if https://github.com/MunifTanjim/nui.nvim/pull/254 improves the situation?

Also try to mount the `row_layout` first. Or if you want to mount `col_layout` first, try using `relative = "win"` for `row_layout`.

```lua
local Layout = require("nui.layout")
local Split = require("nui.split")

local cur_win = vim.api.nvim_get_current_win()

local row_layout = Layout(
  {
    position = "bottom",
    relative = "editor",
    size = "25%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "50%" }),
    Layout.Box(Split({}), { size = "50%" }),
  }, {
    dir = "row",
  })
)

row_layout:mount()
vim.api.nvim_set_current_win(cur_win)

local col_layout = Layout(
  {
    position = "left",
    relative = "editor",
    size = "20%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
  }, {
    dir = "col",
  })
)

col_layout:mount()
vim.api.nvim_set_current_win(cur_win)
```

**Comment by MunifTanjim** [comment]
> I tried calling row_layout:update() (which is similar to how I solved the same issue in nvim-dap-ui) but it seems to make things go a bit wrong 😅

I'll look into the `:update()` issue.

In the meantime, can you try this?

```lua
local Layout = require("nui.layout")
local Split = require("nui.split")

local cur_win = vim.api.nvim_get_current_win()

local col_layout = Layout(
  {
    position = "left",
    relative = "editor",
    size = "20%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
  }, {
    dir = "col",
  })
)

col_layout:mount()
vim.api.nvim_set_current_win(cur_win)

local row_layout = Layout(
  {
    position = "bottom",
    relative = "win", -- makes it (size and position) relative to the focused window
    size = "25%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "50%" }),
    Layout.Box(Split({}), { size = "50%" }),
  }, {
    dir = "row",
  })
)

row_layout:mount()
vim.api.nvim_set_current_win(cur_win)
```

**Comment by rcarriga** [comment]
That works if there's only one window open but with multiple windows, I believe I'll need `relative = "editor"`
![image](https://user-images.githubusercontent.com/24252670/231252585-92a8ca9c-5cb7-4fb1-97be-507217fdb97a.png)

Updated version of my last script to handle going to the first window before opening the layouts (still has the issue with unevenly spaced row_layout windows but can be in any window when opening)
```lua
local Layout = require("nui.layout")
local Split = require("nui.split")

local cur_win = vim.api.nvim_get_current_win()
local first_win = vim.fn.win_getid(1)
vim.api.nvim_set_current_win(first_win)

local col_layout = Layout(
  {
    position = "left",
    relative = "editor",
    size = "20%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
    Layout.Box(Split({}), { size = "25%" }),
  }, {
    dir = "col",
  })
)


local row_layout = Layout(
  {
    position = "bottom",
    relative = "editor",
    size = "25%",
  },
  Layout.Box({
    Layout.Box(Split({}), { size = "50%" }),
    Layout.Box(Split({}), { size = "50%" }),
  }, {
    dir = "row",
  })
)

row_layout:mount()
vim.api.nvim_set_current_win(first_win)
col_layout:mount()
vim.api.nvim_set_current_win(cur_win)
```
![image](https://user-images.githubusercontent.com/24252670/231253111-bfa8fabf-d87d-4a66-9485-72676562adc7.png)

**Comment by MunifTanjim** [comment]
Also here's the PR for improving `layout:update()` behavior:  https://github.com/MunifTanjim/nui.nvim/pull/255

**Comment by MunifTanjim** [comment]
by the way, how do you handle the scenario where a new file is opened in a split when `nvim-dap-ui` is already visible? 🤔

**Comment by rcarriga** [comment]
> Got it. Since 20% of editor width is occupied by col_layout, try using 40% and 40% for row_layout splits?

Ah that's it so all sizes are relative to the editor, I'd assumed that it was only the parent layout size and the children would be relative to the layout

> by the way, how do you handle the scenario where a new file is opened in a split when nvim-dap-ui is already visible? thinking

I set `winfixwidth` and `winfixheight` but it looks like nui prevents them from being set for some reason. Is there a way to set them without breaking nui?

**Comment by MunifTanjim** [comment]
> Ah that's it so all sizes are relative to the editor, I'd assumed that it was only the parent layout size and the children would be relative to the layout

For Layout with floats, that is the case. Because Layout opens a floating window for itself, and then places the children floating windows on top of that window.

But for Layout with splits, we can't do that. All the splits are positioned side by side. That's why the calculation is a bit different.

**Comment by MunifTanjim** [comment]
> I set winfixwidth and winfixheight but it looks like nui prevents them from being set for some reason. Is there a way to set them without breaking nui?

After https://github.com/MunifTanjim/nui.nvim/pull/256 is merged, you can do this:

```lua
local win_options = {
  winfixwidth = true,
  winfixheight = true,
}

Layout.Box(Split({ win_options = win_options }), { size = "40%" })
```

**Comment by MunifTanjim** [comment]
Can you try this with the latest `main` branch now?

```lua
local Layout = require("nui.layout")
local Split = require("nui.split")

local cur_win = vim.api.nvim_get_current_win()

local win_options = {
  winfixwidth = true,
  winfixheight = true,
}

local rl = Layout(
  {
    position = "bottom",
    relative = "editor",
    size = "25%",
  },
  Layout.Box({
    Layout.Box(Split({ win_options = win_options }), { size = "40%" }),
    Layout.Box(Split({ win_options = win_options }), { size = "40%" }),
  }, {
    dir = "row",
  })
)

vim.api.nvim_set_current_win(cur_win)
rl:mount()

local cl = Layout(
  {
    position = "left",
    relative = "editor",
    size = "20%",
  },
  Layout.Box({
    Layout.Box(Split({ win_options = win_options }), { size = "25%" }),
    Layout.Box(Split({ win_options = win_options }), { size = "25%" }),
    Layout.Box(Split({ win_options = win_options }), { size = "25%" }),
    Layout.Box(Split({ win_options = win_options }), { size = "25%" }),
  }, {
    dir = "col",
  })
)

vim.api.nvim_set_current_win(cur_win)
cl:mount()
```

Also thanks for experimenting with it and pointig out these bugs.
