### ISSUE TITLE
bug: input does not work correctly when `default_value` starts with `"p"`

### ISSUE THREAD

**Issue by pysan3** [MunifTanjim/nui.nvim#257]
Hi, thanks for the amazing plugin!.

Over on [neo-tree.nvim](https://github.com/nvim-neo-tree/neo-tree.nvim), we had an interesting issue reporting that when a filename starts with a `"p"` the following several characters do not show up in the placeholder. Ref: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/796

I was able to reproduce this issue with the following code (which is almost identical to the demo).

```lua
local Input = require("nui.input")
local event = require("nui.utils.autocmd").event

local txt_tbl = {
  -- "p--.txt", --> `p.txt`
  "рenglish.txt", --> `"pglish.txt`
  -- "работа.txt", --> "рбота.txt"
}

local txt = txt_tbl[1]

local input = Input({
  position = "50%",
  size = {
    width = 60,
  },
  border = {
    style = "single",
    text = {
      top = "[Howdy?]",
      top_align = "center",
    },
  },
  win_options = {
    winhighlight = "Normal:Normal,FloatBorder:Normal",
  },
}, {
  prompt = "> ",
  default_value = txt,
  on_close = function()
    print("Input Closed!")
  end,
  on_submit = function(value)
    print("Input Submitted: " .. value)
  end,
})

-- mount/open the component
input:mount()

-- unmount component when cursor leaves buffer
input:on(event.BufLeave, function()
  input:unmount()
end)
```

It would be very nice if you could investigate this problem.

---

Interestingly, when I change this line to `vim.fn.feedkeys(...)` the issue is solved.

https://github.com/MunifTanjim/nui.nvim/blob/ecd9def93891b9260b15b5fcef542eaabf4145c9/lua/nui/input/init.lua#L122

**Comment by MunifTanjim** [comment]
Should be fixed now.

**Comment by pysan3** [comment]
Wow, what a quick fix!

Tested and works like a charm. Thanks you very much!
