### ISSUE TITLE
Nui borders are not validated/recreated on mount

### ISSUE THREAD

**Issue by folke** [MunifTanjim/nui.nvim#270]
The latest change on `main` breaks noice in a lot of ways.

The problem is that a border buffer may have been deleted or the border may have been unmounted and border `mount` does no longer create the buffer.
It also doesn't check if the buffer still exists and is valid, leading to a broken view.

I've just pushed a work-around to noice, but would be good to fix this in nui.

https://github.com/folke/noice.nvim/commit/4db3c8f14302273b842f73a8facf1999169c1e41

**Comment by MunifTanjim** [comment]
Sorry about that.

The intention was to allow `border:set_text()` even before mount, just as `popup:on()`, `popup:map()` can be used before mount.

But I forgot to ensure `.bufnr` is still exists during mount (like popup does https://github.com/MunifTanjim/nui.nvim/blob/643e9afb9411f5ebd95efb43437692e74238a4a3/lua/nui/popup/init.lua#L218).

**Comment by MunifTanjim** [comment]
Should be fixed now. And also added tests for this.

**Comment by folke** [comment]
Thank you for the quick fix!
