### ISSUE TITLE
popup border style not support for none

### ISSUE THREAD

**Issue by emxxjnm** [MunifTanjim/nui.nvim#290]
https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/popup/README.md#borderstyle

E5108: Error executing lua: ....local/share/nvim/lazy/nui.nvim/lua/nui/popup/border.lua:677: text not supported for style:none                                                                       
stack traceback:                                                                                                                                                                                     
        [C]: in function 'error'                                                                                                                                                                     
        ....local/share/nvim/lazy/nui.nvim/lua/nui/popup/border.lua:677: in function 'set_style'                                                                                                     
        ....local/share/nvim/lazy/nui.nvim/lua/nui/popup/border.lua:473: in function 'init'                                                                                                          
        .../.local/share/nvim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function 'Border'                                                                                                        
        ...g/.local/share/nvim/lazy/nui.nvim/lua/nui/popup/init.lua:153: in function 'init'                                                                                                          
        ...g/.local/share/nvim/lazy/nui.nvim/lua/nui/input/init.lua:60: in function 'init'                                                                                                           
        .../.local/share/nvim/lazy/nui.nvim/lua/nui/object/init.lua:132: in function 'Input'                                                                                                         
        ...share/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/inputs.lua:36: in function 'input'                                                                                                          
        ....nvim/lua/neo-tree/sources/filesystem/lib/fs_actions.lua:339: in function 'create_node'                                                                                                   
        ...y/neo-tree.nvim/lua/neo-tree/sources/common/commands.lua:98: in function 'add'                                                                                                            
        ...o-tree.nvim/lua/neo-tree/sources/filesystem/commands.lua:20: in function 'func'                                                                                                           
        ...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:830: in function <...are/nvim/lazy/neo-tree.nvim/lua/neo-tree/ui/renderer.lua:828>

**Comment by MunifTanjim** [comment]
It says that "text not supported for style:none". And that is expected. There's no place to put the text if border is `none`.
