### ISSUE TITLE
Nested Layouts

### ISSUE THREAD

**Issue by head-gardener** [MunifTanjim/nui.nvim#292]
Might be missing something, but I can't find a way to nest a row layout in a column layout. Documentation doesn't seem to mention layout nesting.

**Comment by MunifTanjim** [comment]
What do you mean by "nested layout"?

You can arrange the layout boxes however you want. You can find examples in this file: https://github.com/MunifTanjim/nui.nvim/blob/9e3916e784660f55f47daa6f26053ad044db5d6a/tests/nui/layout/init_spec.lua

https://github.com/MunifTanjim/nui.nvim/blob/9e3916e784660f55f47daa6f26053ad044db5d6a/tests/nui/layout/init_spec.lua#L1363-L1376

This is the doc for `Layout.Box`: https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/layout#layoutbox

**Comment by head-gardener** [comment]
Thanks, that's exactly what I was looking for. Maybe this example should be put on docs somewhere?
