### ISSUE TITLE
Noticing some weird behavior with nodes with no children not being expandable

### ISSUE THREAD

**Issue by miversen33** [MunifTanjim/nui.nvim#293]
The long short, it appears that giving a node an empty array for children results in the node not being "expandable".

This can be seen via [the TreeNode:expand function](https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/tree/init.lua#L117-L124).
```lua
---@return boolean is_updated
function TreeNode:expand()
  if self:has_children() and not self:is_expanded() then
    self._is_expanded = true
    return true
  end
  return false
end
```

Checking the source of [TreeNode:has_children](https://github.com/MunifTanjim/nui.nvim/blob/main/lua/nui/tree/init.lua#L101-L105), we see
```lua
---@return boolean
function TreeNode:has_children()
  local items = self._child_ids or self.__children
  return items and #items > 0 or false
end
```

Thus, if I create a node and give it an empty table of children (as opposed to nil), it will return false to `has_children` (which is probably correct) and then will refuse to expand. I am unsure what the recommended approach here is. I am currently attempting to _poorly_ track expansion myself to work around this, but it feels like nodes should be expandable if their children is an empty table (as that would indicate that the node is meant to house children).

Got any tips?

**Comment by MunifTanjim** [comment]
Hey @miversen33, thanks for reporting this. Nodes with 0 child can be expanded now.

**Comment by miversen33** [comment]
I appreciate you!
