### ISSUE TITLE
How can I create a split with a layout?

### ISSUE THREAD

**Issue by harrisoncramer** [MunifTanjim/nui.nvim#297]
Thank you for this library!

The documentation states this is possible but it's not clear to me how this can be done. I'd just like to create a split with two separate halves. Is this accomplished via the Layout component? Is there an example somewhere I could reference?

I've tried this:

```lua
  local top_split = Split({ border = "single" })
  local bottom_split = Split({ border = "double" })

  local layout = Layout(
    {
      position = "50%",
      size = {
        width = 80,
        height = 40,
      },
    },
    Layout.Box({
      Layout.Box(top_split, { size = "40%" }),
      Layout.Box(bottom_split, { size = "60%" }),
    }, { dir = "col" })
  )

  layout:mount()
```

But get the following error:

```
Error executing vim.schedule lua callback: ...r/.local/share/nvim/lazy/nui.nvim/lua/nui/split/init.lua:168: Error executing lua: ...r/.local/sha
re/nvim/lazy/nui.nvim/lua/nui/split/init.lua:169: Vim:E492: Not an editor command: nil 40split
```

Thanks again!

**Comment by MunifTanjim** [comment]
https://github.com/MunifTanjim/nui.nvim/blob/aa1b4c1e05983ff7debd2b4b2788651db099de2f/tests/nui/layout/init_spec.lua#L1299-L1313

`position` and `size` are different for `Layout` with `Split`.

**Comment by MunifTanjim** [comment]
Looks like it's missing in the documentation, I need to update the doc for this.
