### ISSUE TITLE
[BUG] Popup errors out if opened the second time with the same declaration

### ISSUE THREAD

**Issue by vuki656** [MunifTanjim/nui.nvim#30]
In regards to [this discussion](https://github.com/MunifTanjim/nui.nvim/discussions/28#discussioncomment-1169462)

Code used

```lua
M.pop = function()
    local Popup = require("nui.popup")

    local popup = Popup({
        border = {
            style = "rounded",
            highlight = "FloatBorder",
        },
        position = "50%",
        size = {
            width = "80%",
            height = "60%",
        },
    })

    popup:mount()
end
```

Result:
![second open](https://user-images.githubusercontent.com/8104698/129406385-83fb083c-1301-46d0-bc74-62cc8d6864c3.gif)

**Comment by srafi1** [comment]
Same happens to me. The `styles` table gets messed up after the first use. I was able to fix it by passing a copy of the border style table instead of the original table in `lua/nui/popup/border.lua:L251` like so:

```lua
-- put this anywhere in the file
function table.shallow_copy(t)
  local t2 = {}
  for k,v in pairs(t) do
    t2[k] = v
  end
  return t2
end

-- change L251 to
    props.char = table.shallow_copy(styles[style])
```

**Comment by MunifTanjim** [comment]
Hey @srafi1, yes, you're absolutely right! We're messing up the `styles` table after first usage.

You can use the `vim.deepcopy` instead of manually creating `table.shallow_copy` by the way.

Do you want to open a PR to fix this? or should I go ahead and do it? 😃

**Comment by srafi1** [comment]
Didn't know about `vim.deepcopy`. Just submitted a PR. 🚀
