### ISSUE TITLE
[Feature request] Set winblend in border window

### ISSUE THREAD

**Issue by protiumx** [MunifTanjim/nui.nvim#309]
## Description
Currently when using the option `winblend` in the popup, it only applies to the popup window but not to the border, leaving the popup with an unmatched border.
![image](https://github.com/MunifTanjim/nui.nvim/assets/43855513/9d005bb5-ccba-4e9e-adeb-fdf86577c1b9)

## Workaround
Looking at the code, I was able to use `nvim_win_set_option` to add set the `winblend` option in the `border` window
```lua
vim.api.nvim_win_set_option(self.popup.border.winid, 'winblend', 20)
``` 

I could push a PR if the feature makes sense 🚀

**Comment by MunifTanjim** [comment]
Thanks for reporting! This should be fixed now.
