### ISSUE TITLE
max_width string value

### ISSUE THREAD

**Issue by vurtune** [MunifTanjim/nui.nvim#321]
max_width doesn't accept string value ("90%") like width does

**Comment by MunifTanjim** [comment]
Is there a valid use-case for supporting it? 🤔

**Comment by vurtune** [comment]
Yes, Noice.nvim has cmdpopup and has width in auto, that means the width can be more than current nvim width. I think can put a limit with max_width
![20240104_170514](https://github.com/MunifTanjim/nui.nvim/assets/74165007/379d5a49-22ab-4ace-94c4-3a67dcd0dc65)
Top window `min_width = "80%"`
Bot window `width = auto` behavior

**Comment by MunifTanjim** [comment]
This is confusing. I thought you were talking about the `max_width` option for `NuiMenu`: https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/menu#max_width

But looks like you're actually talking about `noice.nvim`.

If it's a feature request for `noice.nvim`, please open an issue here: https://github.com/folke/noice.nvim/issues

**Comment by vurtune** [comment]
I think you're right.
When I set max_width it says: `.local/share/nvim/lazy/noice.nvim/lua/noice/util/nui.lua:185: bad argument #2 to 'min' (number expected, got string)`
