### ISSUE TITLE
[BUG] Can't use Input and Menu in the same file

### ISSUE THREAD

**Issue by fedepujol** [MunifTanjim/nui.nvim#33]
I'm trying to build a complex layout that uses both Input and Menu. I've followed the instructions on how to build up the popups and when Im executing the function that mounts it Nvim gives the following error: 
`E5108: Error executing lua ...nui.nvim\lua\nui\popup\init.lua:219: invalid border char`

If I comment one of the imports (Input or Menu) the error goes away.

**Comment by MunifTanjim** [comment]
Look like #30, which is already fixed. Can you try updating the plugin and see if the error is still there?

**Comment by fedepujol** [comment]
Done! I've updated the plugin and it was gone! Thanks.
