### ISSUE TITLE
[BUG] Closing an input from insert mode does not return to normal mode

### ISSUE THREAD

**Issue by srafi1** [MunifTanjim/nui.nvim#34]
I have `<esc>` mapped to close an input, which it does, but I also expected it to return vim to the mode that it was in before the input mounted. In my case, that was normal mode, but I think generally returning to normal mode makes sense as that usually happens as a result of hitting `<esc>`.

Minimal reproduction:
```lua
local popup_opts = {
  border = {
    style = 'single',
  },
  position = 0,
  size = {
    width = 20,
    height = 1,
  },
  enter = true,
}

local input = require'nui.input'(popup_opts, {
  prompt = "> ",
})
input:mount()
input:map("i", "<esc>", input.input_props.on_close, { noremap = true })
```

**Comment by MunifTanjim** [comment]
Hey @srafi1 , this should be solved now.
