### ISSUE TITLE
Feat(NuiTable): navigate a table by column and rows

### ISSUE THREAD

**Issue by patata3000** [MunifTanjim/nui.nvim#342]
Hello,

Right now, it's not possible to have the informations to move cursor to next row or next column.

I'm trying to move the cursor one row to the left or right (and same for columns up or down). The only solution I find is to use the data in `_` . Am I missing something?

If it's not possible. Do you think it would be a good idea? Would you implement it? If you wouldn't, would you let someone else do it? Do you have any hint to add such a feature?

With all my kindness :heart:

**Comment by MunifTanjim** [comment]
`table:get_cell` now accepts `position` param.

To get the cell top of the cursor position, do `local cell = table:get_cell({ -1, 0 })`.

To jump to that cell, do `vim.api.nvim_win_set_cursor(0, { cell.range[1], cell.range[2] })`
