### ISSUE TITLE
UI glitch (Layout.Box)

### ISSUE THREAD

**Issue by mobily** [MunifTanjim/nui.nvim#343]
Hello! 👋 Thanks for this awesome library! 

I have the following layout structure:

```
local Layout = require("nui.layout")
local Popup = require("nui.popup")

local p1 = Popup({border = "double"})
local p2 = Popup({border = "double"})
local p3 = Popup({border = "double"})
local p4 = Popup({border = "double"})

local layout =
  Layout(
  {
    position = "50%",
    size = {
      width = 80,
      height = 40
    }
  },
  Layout.Box(
    {
      Layout.Box(p1, {size = "50%"}),
      Layout.Box(
        {
          Layout.Box(p2, {size = "50%"}),
          Layout.Box(
            {
              Layout.Box(p3, {size = "50%"}),
              Layout.Box(p4, {size = "50%"})
            },
            {dir = "col", size = "50%"}
          )
        },
        {dir = "row", size = "50%"}
      )
    },
    {dir = "col"}
  )
)

layout:mount()
```

Here's the result:

<img width="860" alt="CleanShot 2024-03-01 at 16 23 06@2x" src="https://github.com/MunifTanjim/nui.nvim/assets/1467712/d59a990f-232a-4c11-a37d-c4cd3d40c856">

I think two rectangles (at the top right) should be displayed at the bottom right. Am I doing something wrong or it's a bug?

**Comment by MunifTanjim** [comment]
Hey @mobily, thanks for reporting this.

Should be fixed with
- #344

**Comment by mobily** [comment]
hello @MunifTanjim 👋 it works right now, thanks for fixing this quickly!
