### ISSUE TITLE
[bug] incorrect rendering of popup

### ISSUE THREAD

**Issue by embe221ed** [MunifTanjim/nui.nvim#354]
hello!

I've recently switched to the [OneDark neovim theme](https://github.com/navarasu/onedark.nvim) and the command line popup started to render incorrectly. after playing with it for a while, I've been able to "resolve" the issue by removing that line:
```lua
vim.api.nvim_command("redraw")
```
in `Border:_open_window` function. however, I don't think this is the correct fix.

## how it looks without the mentioned change:
<img width="1401" alt="Screenshot 2024-03-20 at 09 39 24" src="https://github.com/MunifTanjim/nui.nvim/assets/26097838/3b0b11f9-468c-4167-acec-2fc988f118c4">

## how it looks after removing the `redraw` line:
<img width="1390" alt="Screenshot 2024-03-20 at 09 39 40" src="https://github.com/MunifTanjim/nui.nvim/assets/26097838/4512ea15-d127-4f2a-9eb2-cb4bf2aaa566">

**Comment by embe221ed** [comment]
ah, sorry for that. I'll try to prepare a minimal setup that reproduces the issue

**Comment by embe221ed** [comment]
this is my full config: https://github.com/embe221ed/scripts/tree/main/configs/nvim

**Comment by MunifTanjim** [comment]
I'm sorry, but I'll need minimal repro code. I can't go through your whole config to find out what's wrong.

> I've recently switched to the [OneDark neovim theme](https://github.com/navarasu/onedark.nvim) and the command line popup started to render incorrectly.

Since it was working for you before, chances are it's not a bug with `nui.nvim`. Try switching back to your old config/theme and see if the issue persist.

**Comment by embe221ed** [comment]
hello, I've tried to reproduce the issue with a minimal setup but failed to do so. I think we can close this issue due to that reason.
