### ISSUE TITLE
Nui, via noice, resize my terminal on exit from neovim.

### ISSUE THREAD

**Issue by kierun** [MunifTanjim/nui.nvim#370]
This is a really strange one, see GIF below and [this issue on contour](https://github.com/contour-terminal/contour/issues/1516)

![nvim-contour-bug](https://github.com/MunifTanjim/nui.nvim/assets/3079575/74d0b6e2-708b-4a56-b564-c5877e20ce3d)

I tried to remove all the plugins, found out it was [noice](https://github.com/folke/noice.nvim). While opening a bug, I tried with their default config and the bug is not reproducible.

**Comment by MunifTanjim** [comment]
It's very unlikely that `nui.nvim` or `noice.nvim` would cause this.

Is this reproducible in any other terminal? It's most probably a bug on the particular terminal emulator you're using.

**Comment by kierun** [comment]
[folke/noice.nvim/issues/688](https://github.com/folke/noice.nvim/issues/688)
