### ISSUE TITLE
Consider using the same z-index for borders

### ISSUE THREAD

**Issue by fredizzimo** [MunifTanjim/nui.nvim#372]
[Neovide](https://github.com/neovide/neovide) can draw shadows and blur underneath floating windows and the current strategy for that is to group the windows by z-index. At some point we might support overriding it, but that needs support from Neovim for a new per windows setting that is transferred to the GUI. And even if that is added, I think per layer grouping should be the default, otherwise a lot of plugins in the Neovim echosystem will have to be changed.

Other similar libraries, like plenary draws the borders with the same z-index as the main window, and that works fine with Neovide, but using separate indices like NUI causes problems like the one below, because the borders cast shadows onto the editbox part.

![image](https://github.com/MunifTanjim/nui.nvim/assets/9946255/e212a65a-2d07-4fdc-b2d9-13bef7d6058c)

Would it be possible for NUI to draw borders the same way? Or at least have an option for it?

NOTE: the current Neovide release 0.13.1 does not yet draw the layers exactly as described, but the latest main version does, with the fix added by this https://github.com/neovide/neovide/pull/2612.

**Comment by MunifTanjim** [comment]
@fredizzimo can you try https://github.com/MunifTanjim/nui.nvim/pull/373 and see if it works alright?
