### ISSUE TITLE
`popup:mount()` doesn't enter the popup if called from empty buffer

### ISSUE THREAD

**Issue by jghauser** [MunifTanjim/nui.nvim#374]
In my plugin, I want to trigger a popup on startup under certain conditions (that don't matter here). My plugin loads only for certain filetypes. In my test setup I start neovim always with `nvim -c "e test.md"` so that the plugin starts automatically. `test.md` isn't a file that exists, so this starts neovim with an empty buffer. When I do this, the popup gets rendered correctly but (even with `enter = true`), the popup isn't in focus. If I create a `test.md` file before running neovim, then everything works as expected.

Not many of my users are going to run into this issue (as it's more likely that my plugin gets loaded when they open some existing file), but it would be nice if nui handled these two cases in the same way.

Btw. Great plugin, it really has made making mine so much easier!

EDIT: Hold on a second, maybe I'm doing something else wrong.

**Comment by jghauser** [comment]
Ok, I'm still not sure what exactly is wrong with my setup, but I'm sure it's not what I thought. Closing this!

**Comment by MunifTanjim** [comment]
Try mounting inside `vim.schedule`, i.e.

```lua
vim.schedule(function()
  popup:mount()
end)
```

chances are the popup is getting focused, but after that your vim is focusing something else.

**Comment by jghauser** [comment]
Thanks @MunifTanjim, that's very helpful!
