### ISSUE TITLE
How i can remove the shadow or drop shadow 

### ISSUE THREAD

**Issue by sheenazien8** [MunifTanjim/nui.nvim#382]
![Screenshot 2024-08-28 at 09 01 50](https://github.com/user-attachments/assets/1682fef7-860e-4959-84f6-4c804d423d8c)

I've tried to change all over the config for style, but the drop shadow is still in there

**Comment by MunifTanjim** [comment]
It's an issue with the colorscheme you're using. Not a bug in nui.nvim

**Comment by sheenazien8** [comment]
thanks @MunifTanjim ya, it's from my colorschme
