### ISSUE TITLE
Event on tree node selection change

### ISSUE THREAD

**Issue by oclay1st** [MunifTanjim/nui.nvim#386]
Hello, thanks for this amazing plugin,
Is there any way to react on tree node selection? .Thanks in advance

**Comment by MunifTanjim** [comment]
What do you mean by tree node selection? `nui.nvim` doesn't provide any selection feature for tree nodes. 🤔

**Comment by oclay1st** [comment]
Sorry, I'm new developing plugins for Neovim and my issue is probably not related to nui, but I wanted to create an interface where whenever any node in the left tree is selected, the right tree is updated.
![Screenshot_20240926_134724](https://github.com/user-attachments/assets/0abc6c92-efd3-47f2-95fa-d995be22e0b2)
I managed to do it reacting to the **CursorMoved** event. Do you think that is an acceptable solution?. Thanks

**Comment by MunifTanjim** [comment]
> I managed to do it reacting to the CursorMoved event. Do you think that is an acceptable solution?

Ah, yes. That is what I would have suggested. Using `CursorMoved` event is the solution.
