### ISSUE TITLE
 support truncating Chinese characters based on the maximum width.

### ISSUE THREAD

**Issue by Kurama622** [MunifTanjim/nui.nvim#392]
https://github.com/MunifTanjim/nui.nvim/pull/391

The `sub` function of the `string` class has issues when truncating Chinese characters: 
1. There will be display issues 
2. There will be issues with length calculation.
![image](https://github.com/user-attachments/assets/a6469343-6de5-49df-a01a-36a281628b34)

I believe that the display width of each character should be calculated.
![image](https://github.com/user-attachments/assets/fb621066-bb2d-48bd-899a-5e6911c94141)

I have implemented a version of the code that supports truncating Chinese characters based on your coding style. Perhaps this does not meet your requirements for the code, and you can raise CR comments for me to modify, or you can also implement your own version.

Finally, thank you for open-sourcing the nui.nvim project; it's truly fantastic!

**Comment by MunifTanjim** [comment]
This should be fixed now. Thanks for your contribution to `nui.nvim` 💜

**Comment by Kurama622** [comment]
Your implementation is much more concise than mine, thank you for the optimization.
