### ISSUE TITLE
[question] how to make the popup untouchable by the cursor

### ISSUE THREAD

**Issue by alexzanderr** [MunifTanjim/nui.nvim#41]
```lua
local Popup = require("nui.popup")
local event = require("nui.utils.autocmd").event

-- https://github.com/MunifTanjim/nui.nvim/tree/main/lua/nui/popup
local popup = Popup({
    enter = false,
    focusable = false,
    relative = "win",
    border = {},
    position = {
        row = 37,
        col = 3,
    },
	-- zindex = 50,
    size = {
        width = 150,
        height = 1,
    },
    buf_options = {
        modifiable = true,
        readonly = false,
    },
    win_options = {
        winblend = 10,
        winhighlight = "Normal:Normal",
    },
})





function FloatingWindow()
    -- mount/open the component
    popup:mount()

    -- unmount component when cursor leaves buffer
	--     popup:on("InsertLeave", function()
	--
	-- )
	local lsp_status = "class Something > def __init__ > for i in range(3): > self.x = 3"
	vim.api.nvim_buf_set_lines(popup.bufnr, 0, 1, false, {
		lsp_status,
	})


    -- set content

end

vim.cmd("autocmd InsertLeave * lua FloatingWindow()")
```

i tried to create a floating window that displays the current tree sitter location
![image](https://user-images.githubusercontent.com/54772464/134786508-5e4626de-c7f0-4863-9b42-e2a652177435.png)

its doing great. but the problem is that i can hover with the cursor over it.
![image](https://user-images.githubusercontent.com/54772464/134786534-063b0c31-8fb2-402d-97e6-44d8f0f15b43.png)

in above photo, my cursor is actually on the 
![image](https://user-images.githubusercontent.com/54772464/134786537-615e8bec-23c1-4214-bd11-df309d619403.png)

print statement, but also the floating window its over it, its floating.

the question is, how do i make this floating window `rock solid` just like statusline (to not hover with the cursor anymore and not to see background text in it (make it none transparent))

**Comment by alexzanderr** [comment]
btw, very cool plugin and this is not an issue, this is more a documentation request

**Comment by MunifTanjim** [comment]
> not to see background text in it (make it none transparent)

That's what `winblend` does. Set `winblend = 0` (check: `:h 'winblend'`)

> how do i make this floating window rock solid just like statusline

Are you sure you want a floating window here? Maybe you're looking for something else? I'm not completely sure about exactly what behavior you're looking for... are you sure it can be done with Neovim?

If you know any plugins that does similar thing, you can take a look at their source code to see how it's done.
