### ISSUE TITLE
Text in popup border and border styling not working

### ISSUE THREAD

**Issue by madskjeldgaard** [MunifTanjim/nui.nvim#44]
Hi ! First of all thanks for this great plugin. I am using it for a project now using the Popup api and it generally works really nicely. But I cannot for the life of me get the border text to work. Below is an example - I should expect this to put the text "yo" in the top border, but I don't see it. Am I missing something?

```lua
Popup({
		enter = true,
		focusable = true,
		border = {
			style = "solid",
			highlight = "FloatBorder",
			text = {
				top = "yo",
				top_align = "center",
			},
		},
		position = "50%",
		size = {
			width = "80%",
			height = "80%",
		},
		buf_options = {
			modifiable = true,
			readonly = false,
			filetype = "supercollider",
		},
		win_options = {
			winblend = 5,
			winhighlight = "Normal:Normal",
		},
	})
```

I also tried using the set_text method: ```popup.border:set_text("top", "sc", "center")``` but still no luck. Am I doing something wrong here or is it a bug? Thanks a lot for your help!

**Comment by madskjeldgaard** [comment]
Changing border.style to "rounded" also doesn't seem to make a difference

**Comment by MunifTanjim** [comment]
Hey @madskjeldgaard , I used the exact code above and got this:

![image](https://user-images.githubusercontent.com/8050659/139541222-612b6616-f55f-4f16-ae80-e1cdc130e48a.png)

Can you pull the latest version of `nui.nvim` and try again?

**Comment by madskjeldgaard** [comment]
That's so strange.  I tried pulling again but no luck.

Are there any global options in nvim that might interfere with this? Here is a full but minimal example I just tried again with no luck:
``` 

function M.what()
	local popup = Popup({
		enter = true,
		focusable = true,
		order = {
			style = "solid",
			highlight = "FloatBorder",
			text = {
				top = "yooooooo",
				top_align = "center",
			},
		},
		position = "50%",
		size = {
			width = "80%",
			height = "60%",
		},
		buf_options = {
			modifiable = true,
			readonly = false,
		},
	})

	-- mount/open the component
	popup:mount()

	-- unmount component when cursor leaves buffer
	popup:on(event.BufLeave, function()
		popup:unmount()
	end)

	-- set content
	vim.api.nvim_buf_set_lines(popup.bufnr, 0, 1, false, { "Hello World" })
end
```

When calling this function, I get this:

![screenshot-30-10-21-19_0327](https://user-images.githubusercontent.com/22474608/139542315-79b3a371-dbcd-4abb-a529-f15a999d306d.png)

**Comment by madskjeldgaard** [comment]
and: thanks for the help!

**Comment by madskjeldgaard** [comment]
> That's so strange. I tried pulling again but no luck.
> 
> Are there any global options in nvim that might interfere with this? Here is a full but minimal example I just tried again with no luck:
> 
> ```
> 
> function M.what()
> 	local popup = Popup({
> 		enter = true,
> 		focusable = true,
> 		order = {
> 			style = "solid",
> 			highlight = "FloatBorder",
> 			text = {
> 				top = "yooooooo",
> 				top_align = "center",
> 			},
> 		},
> 		position = "50%",
> 		size = {
> 			width = "80%",
> 			height = "60%",
> 		},
> 		buf_options = {
> 			modifiable = true,
> 			readonly = false,
> 		},
> 	})
> 
> 	-- mount/open the component
> 	popup:mount()
> 
> 	-- unmount component when cursor leaves buffer
> 	popup:on(event.BufLeave, function()
> 		popup:unmount()
> 	end)
> 
> 	-- set content
> 	vim.api.nvim_buf_set_lines(popup.bufnr, 0, 1, false, { "Hello World" })
> end
> ```
> 
> When calling this function, I get this:
> 
> ![screenshot-30-10-21-19_0327](https://user-images.githubusercontent.com/22474608/139542315-79b3a371-dbcd-4abb-a529-f15a999d306d.png)

Ah sorry, had a typo - order should be border of course.

**Comment by madskjeldgaard** [comment]
I should mention:
```
nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Kompileret af builduser

Features: +acl +iconv +tui
See ":help feature-compile"

    system vimrc-fil: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```

And running on Arch Linux.

**Comment by MunifTanjim** [comment]
Does the border appear if you don't use `border.text`?

```
    border = {
      style = "rounded",
      highlight = "FloatBorder",
    },
```

**Comment by madskjeldgaard** [comment]
> Does the border appear if you don't use `border.text`?
> 
> ```
>     border = {
>       style = "rounded",
>       highlight = "FloatBorder",
>     },
> ```

Jep! curiusly though I can't tell the difference between rounded, single and double. They look the same here. Shadow and none work fine.

**Comment by MunifTanjim** [comment]
I wonder if this is a font issue 🤔 Which font are you using?

Can you try using one of the Nerd Fonts? https://aur.archlinux.org/packages/nerd-fonts-complete/

**Comment by madskjeldgaard** [comment]
> I wonder if this is a font issue thinking Which font are you using?
> 
> Can you try using one of the Nerd Fonts? https://aur.archlinux.org/packages/nerd-fonts-complete/

Ah that sounds correct! I am using Adobe Source Code Pro in Kitty.

**Comment by MunifTanjim** [comment]
Let me know if changing font fixes it, otherwise we'll need to investigate further to find the bug 😄

**Comment by madskjeldgaard** [comment]
> Let me know if changing font fixes it, otherwise we'll need to investigate further to find the bug smile

Thanks for the tip. I tried again with a nerd font set in Kitty, and it didn't do the trick. Also tried in Alacritty just to check and it doesnt work there either.

**Comment by madskjeldgaard** [comment]
This works now it seems. Thanks!
