### ISSUE TITLE
Use NuiText as/with MenuItem and MenuSeparator

### ISSUE THREAD

**Issue by mattleong** [MunifTanjim/nui.nvim#58]
Hi! First off... I'm in love with this plugin. You've done a fantastic job. 

Anyways, similar to how you can now use NuiText as the border text on a popup.. I think it would be great to add the same improvements to Menu.

In order to simplify the process of building a dynamic menu, it would be really great if NuiText could be used but Menu.item/Menu.separator in order to easily apply highlights to menu items. 

I was thinking usage similar to below would be pretty convenient.

```
Menu.separator(NuiText('some text'))
Menu.item(NuiText('some text'), {})
``` 

Not sure if you've already thought about this but it would be amazingly helpful for the new plugin I am working on.

**Comment by MunifTanjim** [comment]
Yep, this was already planned. 😃

**Comment by mattleong** [comment]
Ah awesome, I was half expecting that would be the case 😄

**Comment by MunifTanjim** [comment]
You can try out the PR #61 if you want.

It'll be merged once I'm done writing the automated tests for it.
