### ISSUE TITLE
Add NuiTree example from PR into official docs

### ISSUE THREAD

**Issue by cseickel** [MunifTanjim/nui.nvim#70]
I think the example given in https://github.com/MunifTanjim/nui.nvim/pull/49 is critical to understanding how to use the tree and should be lifted out of the PR to somewhere more prominent. Maybe on the wiki with a link on the NuiTree docs page, or just directly into the NuiTree docs page.

**Comment by MunifTanjim** [comment]
Added wiki page link for all blocks/components.

Added the nui.tree example in: https://github.com/MunifTanjim/nui.nvim/wiki/nui.tree#example-from-pr-49
