### ISSUE TITLE
Mount popup displaying in it a buffer that already exists

### ISSUE THREAD

**Issue by xeluxee** [MunifTanjim/nui.nvim#88]
Hi, thanks for making plugin

I'd like to create a popup to display inside a buffer that already exists, so I've tried the following
``` lua
local popup = nui_popup(popup_settings)
popup:mount()
vim.api.nvim_win_set_buf(popup.winid, already_existing_bufnr)
```

Everything looks ok but when I try to unmount the popup it isn't closed and its content gets deleted.
No idea why no error message is printed.

So what's the right way to do this?

**Comment by vuki656** [comment]
Not sure if the same but check  #29

**Comment by MunifTanjim** [comment]
> I'd like to create a popup to display inside a buffer that already exists

Hey @xeluxee , I've been thinking of additing support for this use-case for quite some time... but haven't yet started to work on it. So, currently it is not possible to do so. But this feature will be available soon. 😃

**Comment by xeluxee** [comment]
> Not sure if the same but check #29

@vuki656 that's not the case since I've already set a keymap to close popup
Here's full code
``` lua
local nui_popup = require("nui.popup")

local popup_settings = {
  enter = true,
  focusable = true,
  border = {
    style = "rounded",
    text = {
      top = " NUI Popup ",
      top_align = "center",
    },
  },
  relative = "editor",
  position = "50%",
  size = "50%",
  buf_options = {
    modifiable = false,
    readonly = false,
  },
  win_options = {
    number = true,
    relativenumber = true,
  },
}

local popup = nui_popup(popup_settings)
popup:mount()
vim.api.nvim_win_set_buf(popup.winid, 20)

popup:map('n', 'q', function()
  popup:unmount()
end, { noremap = true })
```

@MunifTanjim the issue is that when another buffer is displayed inside popup the keybindings associated with that buffer are considered, so keymaps created with `popup:map` are ignored and pressing `q` doesn't close the popup

**Comment by MunifTanjim** [comment]
@xeluxee Now you can pass `bufnr` in the popup options:

```lua
local popup = Popup({
  -- instead of `vim.api.nvim_win_set_buf(popup.winid, 20)`
  bufnr = 20,
  ...
})
```

**Comment by xeluxee** [comment]
@MunifTanjim thanks, it works
